import Head from 'next/head'

export default function Blog() {
    return (
        <>

            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className='bg-light-gray'>
                <h1 className=''>
                    Blog
                </h1>
            </main>

        </>
    )
}
