import Head from 'next/head'

export default function Blog() {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className='bg-light-gray'>
                <h1 className=''>
                </h1>
                <iframe 
                    src='https://widgets.sociablekit.com/linkedin-page-posts/iframe/211783' 
                    frameborder='0' 
                    width='100%' 
                    height='1000'
                />
            </main>
        </>
    )
}