import Head from 'next/head'

export default function Blog() {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className='bg-light-gray'>
                <h1 className=''>
                </h1>
                <div 
                    dangerouslySetInnerHTML={{
                        __html: `
                            <div class='sk-ww-linkedin-page-post' data-embed-id='211783'></div>
                            <script src='https://widgets.sociablekit.com/linkedin-page-posts/widget.js' async defer></script>
                        `
                    }}
                />
            </main>
        </>
    )
}