import Head from 'next/head'
import Link from 'next/link'
import Hero from '@/components/hero'
import Showcase from '@/components/showcase'

export default function Home() {

    return (
        <>

            <Head>
                <title>DRIFT - Drone Research and Intelligent Flight Technology</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className='bg-light-gray'>

                <Hero />
                <Showcase />

                <section className='bg-blue text-white px-8 py-16 flex flex-col items-center text-center gap-4 md:gap-6'>
                    <h2 className='font-semibold text-xl md:text-4xl'>
                        Interested in working with us?
                    </h2>
                    <p className='md:text-xl md:whitespace-pre-line'>
                        We are always actively looking for companies to work with {'\n'} and motivated undergraduates to join our team!
                    </p>
                    <Link href='/contact' className="bg-white font-semibold text-black px-5 py-2 rounded-full">
                        Learn more
                    </Link>
                </section>
                
                <section>

                </section>

            </main>

        </>
    )
}
