import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Hero from '@/components/hero'

export default function Home() {
    return (
        <>

            <Head>
                <title>DRIFT - Drone Research and Intelligent Flight Technology</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className='bg-light-gray'>

                <Hero />

                <section>
                    
                </section>

                <section>

                </section>
                
                <section>

                </section>

            </main>

        </>
    )
}
