import Head from 'next/head'

export default function People() {

    const team = [
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
        {
            image: 'team/nicholas_ly.jpg',
            name: 'Nicholas Ly',
            position: 'Software Engineer',
        },
    ]

    return (
        <>

            <Head>
                <title>People</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main className='bg-light-gray'>

                <section className='flex justify-center py-16'>
                    <div className='px-6'>
                        <h1 className='font-bold text-3xl sm:text-4xl'>
                            Research for the future, by the future.
                        </h1>
                        <p className='mt-4 text-xl max-w-4xl leading-8'>
                            Our passion undegraduate team is solving complex problems by developing extraordinary flight technology.
                        </p>
                        <p className='mt-8 max-w-4xl leading-7'>
                            Founded by students, for students, our team will continue to be an opportunity for undergraduates to jump start their career through advanced, real world engineering problems.
                        </p>
                        <p className='mt-4 max-w-4xl leading-7'>
                            We are completely funded by grants, investments, and sponsors who support our mission to revolutionize drones.
                        </p>
                        <h1 className='font-bold text-3xl sm:text-4xl mt-16'>
                            Never done innovating.
                        </h1>
                        <p className='mt-4 max-w-4xl leading-7'>
                            We're extremely proud of our team, and we're honored others have taken notice. Our team has interned or accepted offers from these great companies.
                        </p>
                        <div class="mx-auto mt-16 grid grid-cols-4 items-center gap-y-12 sm:grid-cols-6">
                            <img class="col-span-2 max-h-8 sm:max-h-10 md:max-h-12 w-full object-contain" src="company_logos/amazon.png" alt="Amazon" />
                            <img class="col-span-2 max-h-8 sm:max-h-10 md:max-h-12 w-full object-contain" src="company_logos/ford.png" alt="Ford" />
                            <img class="col-span-2 max-h-8 sm:max-h-10 md:max-h-12 w-full object-contain" src="company_logos/bosch.png" alt="Bosch" />
                            <img class="col-span-2 max-h-5 sm:max-h-6 md:max-h-7 w-full object-contain sm:col-start-2" src="company_logos/blueflite.png" alt="Blueflite" />
                            <img class="col-span-2 col-start-2 max-h-7 sm:max-h-8 md:max-h-10 w-full object-contain sm:col-start-auto" src="company_logos/northrop_grumman.png" alt="Northrop Grumman" />
                        </div>
                    </div>
                </section>

                <section className='flex justify-center py-16 bg-white'>
                    <div className='px-6'>
                        <h1 className='font-bold text-3xl sm:text-4xl mb-12'>
                            Meet our team.
                        </h1>
                        <div className='grid gap-16 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
                            {team.map(({ image, name, position }) => (
                                <div className='flex flex-col items-center'>
                                    <img class="rounded-full max-h-64 object-cover mb-4 shadow-xl" src={image} alt={name} />
                                    <text className='text-lg font-semibold leading-7 tracking-tight'>{name}</text>
                                    <text className='text-base font-semibold leading-6 text-blue'>{position}</text>
                                </div>
                            ))}
                        </div>
                    </div>
                </section>

            </main>

        </>
    )
}
