import Head from 'next/head'

export default function Research() {
    return (
        <>

            <Head>
                <title>Research</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <main>
                <h1 className=''>
                    Research
                </h1>
            </main>

        </>
    )
}
