import Head from 'next/head'
import Image from 'next/image'

export default function Sponsors() {

    const data = [
        {
            image: '/photos/aided.png',
            alt: 'An image of SQUAB-2, a prototype delivery drone used for testing.',
            title: 'Sponsor DRIFT',
            subtitle: 'Do it.'
        }
    ]

    return (
        <>

            <Head>
                <title>Sponsors</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>

            <div className='my-8'>
    <iframe title='Fueling Breakthroughs in Drone Technology' src='https://www.gofundme.com/f/fueling-breakthroughs-in-drone-technology/widget/large' width='100%' height='600' frameBorder='0'></iframe>
</div>

        </>
    )
}
